### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by ran12201** [sxyu/pixel-nerf#26]
Hi, I can't get rid of this error no matter what I try. It seems to be possibly related somehow to the train.py having two "-1" in it. It pops up after about 10 or so minutes of training. I'm trying to do a custom data set that atm has 18 items with 98 frames in the "train" folder, and 3 items with 98 frames as well in both the val and test folders. I'm using the srn format, and have checked and rechecked that there are no indexing errors that I can find as far as having correct and corresponding numbers of items in all folders. Here is my error readout. I'm on Windows 10, 1 Nvidia 970. Thank you so much. 

[ 2.16s/it] EXPERIMENT NAME: shoes2
CONTINUE? yes
* Config file: conf/exp/shoe.conf
* Dataset format: srn
* Dataset location: C:\shoes_dataset\shoes
Loading SRN dataset C:\shoes_dataset\shoes_train name: shoes
Loading SRN dataset C:\shoes_dataset\shoes_val name: shoes
Loading SRN dataset C:\shoes_dataset\shoes_test name: shoes
dset z_near 0.8, z_far 1.8, lindisp False
Using torchvision resnet34 encoder
[ 3.62s/it] C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: block: [0,
0,0], thread: [78,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` fa
iled.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: block: [0,0,0], thread
: [79,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
C:/cb/pytorch_1000000000000/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: block: [0,0,0], thread
: [80,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "train/train.py", line 343, in <module>
    trainer.start()
  File "C:\pixel-nerf-master\train\trainlib\trainer.py", line 162, in start
    losses = self.train_step(data, global_step=step_id)
  File "train/train.py", line 220, in train_step
    return self.calc_losses(data, is_train=True, global_step=global_step)
  File "train/train.py", line 173, in calc_losses
    rays = cam_rays.view(-1, cam_rays.shape[-1])[pix_inds].to(
RuntimeError: CUDA error: device-side assert triggered

**Comment by Viki1314** [comment]
I meet the same problem.It is cause by the pix_indxs which has the element that is bigger than cam_rays.shape[0].
```python
def bbox_sample(bboxes, num_pix):
    """
    :param 
    bboxes:(NV, 4) ,cmin rmin cmax rmax
    num_pix:int,128
    :return (num_pix, 3)
    """
    image_ids = torch.randint(0, bboxes.shape[0], (num_pix,))#[0,NV),shape:128
    pix_bboxes = bboxes[image_ids]#128x4
    # x = (
    #     torch.rand(num_pix) * (pix_bboxes[:, 2] + 1 - pix_bboxes[:, 0])
    #     + pix_bboxes[:, 0]
    # ).long()#128
    # y = (
    #     torch.rand(num_pix) * (pix_bboxes[:, 3] + 1 - pix_bboxes[:, 1])
    #     + pix_bboxes[:, 1]
    # ).long()#128
    x = (
        torch.rand(num_pix) * (pix_bboxes[:, 2]  - pix_bboxes[:, 0])
        + pix_bboxes[:, 0]
    ).long()#128
    y = (
        torch.rand(num_pix) * (pix_bboxes[:, 3]  - pix_bboxes[:, 1])
        + pix_bboxes[:, 1]
    ).long()#128
    pix = torch.stack((image_ids, y, x), dim=-1)
    return pix
```
