### ISSUE TITLE
pyhocon problem

### ISSUE THREAD

**Issue by chiyaohuang** [sxyu/pixel-nerf#61]
Hi,

I met a pyhocon problem. when I try the eval ''python eval/gen_video.py  -n sn64 --gpu_id 0 --split test -P '2'  -D ~/disk/NMR_Dataset -S 0", it shows

pyparsing.exceptions.ParseException: Expected '}', found '='  (at char 759), (line:34, col:18)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval/gen_video.py", line 63, in <module>
    args, conf = util.args.parse_args(extra_args)
  File "/home/yao/pixel-nerf/src/util/args.py", line 99, in parse_args
    conf = ConfigFactory.parse_file(args.conf)

Does anyone know how to solve it?

**Comment by lisenbuaa** [comment]
I also face the same problem.

**Comment by chiyaohuang** [comment]
I reinstall the older version of pyhocon and solve the problem.

Try:
pip install --force-reinstall -v "pyhocon==0.3.55"

**Comment by lisenbuaa** [comment]
> 

Thank you! I solve it.

**Comment by lmd-ch** [comment]
That solves the problem, thank you very much.
