### ISSUE TITLE
Can't run successfully：python eval/gen_video.py -n srn_car --gpu_id 1 --split test -P '64 104' -D data/srn_cars -S 1

### ISSUE THREAD

**Issue by HuaandQi** [sxyu/pixel-nerf#66]
hello, is there any solution for this problem？
python eval/gen_video.py -n srn_car --gpu_id 1 --split test -P '64 104' -D data/srn_cars -S 1

* Config file: conf/exp/srn.conf
* Dataset format: srn
* Dataset location: data/srn_cars
Loading SRN dataset data/srn_cars_test name: srn_cars
Traceback (most recent call last):
  File "eval/gen_video.py", line 68, in <module>
    dset = get_split_dataset(
  File "/home/hua/pixel-nerf/src/data/__init__.py", line 62, in get_split_dataset
    test_set = dset_class(datadir, stage="test", **flags, **kwargs)
  File "/home/hua/pixel-nerf/src/data/SRNDataset.py", line 29, in __init__
    assert os.path.exists(self.base_path)
AssertionError

**Comment by Henry-Bi** [comment]
Hi, i met the same issues, and i have solved. You can use `print(self.base_path)` before line 29 in  File "/home/hua/pixel-nerf/src/data/SRNDataset.py",  and check the direction compared with the your dataset location.
